### ISSUE TITLE
Issue when deleting entry types

### ISSUE THREAD

**Issue by Anubarak** [nfourtythree/craft3-entriessubset#1]
When you create a new field and delete an entryType selected in this field afterwards it will throw an error. Would you mind to check if the fetched entry type is not null please?

https://github.com/nfourtythree/craft3-entriessubset/blob/master/src/fields/EntriesSubset.php#L121

```php
protected function inputTemplateVariables( $value = null, ElementInterface $element = null ): array
{
  $vars = parent::inputTemplateVariables( $value, $element );
  
  $settings = $this->getSettings();
  
  
  if ( isset( $settings[ 'entryTypes' ] ) ) {
	$entryTypes = $settings[ 'entryTypes' ];
	
	if ($entryTypes and is_array( $entryTypes ) and !empty( $entryTypes ) ) {
	  foreach( $entryTypes as $typeId ) {
		if ( is_numeric( $typeId ) ) {
		  $entryType = Craft::$app->sections->getEntryTypeById( $typeId );
		  if($entryType !== null){     //  <--- just check if it's not null so $entryType->handle won't throw an exception  
			$vars[ 'criteria' ][ 'type' ][] = $entryType->handle;
		  }
		}
	  }
	}
  }

  return $vars;
}
```

Otherwise we would have to include your plugin to our git in order to keep this change into all our projects.

Thank you very much

**Comment by nfourtythree** [comment]
@Anubarak thanks for spotting this! 👍

Have pushed an update and a release, let me know if there are any issues!
