### ISSUE TITLE
How to Completely Remove

### ISSUE THREAD

**Issue by k7y6t5** [nfourtythree/craft3-entriessubset#16]
We're no longer using our licensed version of EntriesSubset on our Craft 3 site and I need to completely remove it. 

I used Settings > Plugins > EntriesSubset > Uninstall and now only see Install as an option in the dropdown. The plugin's status is Missing. I've run `$ composer remove` and have confirmed that the plugin files are no longer in /vendor. The plugin is not mentioned anywhere in composer.json or composer.lock. It also doesn't appear in the craft_plugins table.

When I load Settings > Plugins, the installed plugins display immediately and then EntriesSubset appears after a short pause. I am not logged into our Craft ID account.

**Comment by nfourtythree** [comment]
Hi @k7y6t5 

This sounds like the same issue as: https://github.com/craftcms/cms/issues/4525

The solution is to do the following:

> plugin licenses automatically attach themselves to the Craft license whenever an API request comes in that shows that they are being used together.

Thanks!
