### ISSUE TITLE
Installation via Composer failed because I'm doing the false way

### ISSUE THREAD

**Issue by dueddel** [nfourtythree/craft3-entriessubset#4]
When invoking a `composer require …` as stated in the README file I get an error message.

>   [InvalidArgumentException]
>   Could not find a matching version of package nfourtythree/craft3-entriessubset. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

I also couldn't find the lib on http://packagist.org/…

I then realized that there is no way of installing it manually. It's a plugin to be installed via Craft's new plugin store.

Please, change the README file's content. It currently leads people to waste time on (not) installing things they actually can't install the documented way.

Thanks. :)

**Comment by nfourtythree** [comment]
Hi @dueddel 

Thanks for bringing this to my attention, I was sure I had set all of this up!

Good catch should be all sorted now.

Thanks!

**Comment by dueddel** [comment]
Wow, unexpectedly fast response. Thank you for adding this one to Packagist. 👍 
I directly updated my anser on Stackexchange where I initially came from:
https://craftcms.stackexchange.com/a/25732/3792
