### ISSUE TITLE
Entries Subset Breaks on Latest Craft Version

### ISSUE THREAD

**Issue by mattcdavis1** [nfourtythree/craft3-entriessubset#7]
I just updated Craft to `Craft Pro 3.1.2.2` and the entries subtype settings seem to no longer work correctly.  When I select certain channels the types for that channel are grayed-out and unselectable.

Example: 
[Accessories Channel Selected](https://drive.google.com/a/union.co/file/d/1TdWfE6Wvke8Uo73JZ70NbY5a21dtSrrq/view?usp=drivesdk)
[Accessories Types Grayed Out](https://drive.google.com/a/union.co/file/d/1zfxT73y_7vq7knPjTBe1ybCJCIk3ma8W/view?usp=drivesdk)

**Comment by nfourtythree** [comment]
Hey @mattcdavis1 

Thanks for pointing this out I will take a look and see what is going on 👍

**Comment by nfourtythree** [comment]
Just to provide an update, I have verified the issue and pushed some changes to the dev branch that should fix the issue. Haven't had a chance to fully test yet, hence no release.

It is there if you fancy testing it out @mattcdavis1, hopefully, get it rolled out properly soon.

**Comment by nfourtythree** [comment]
Just pushed a release for this 👍
