### ISSUE TITLE
Reverse Relations Compatibility

### ISSUE THREAD

**Issue by tinchalamo** [nfourtythree/craft3-entriessubset#9]
Would it be possible to make this compatible with the [Reverse Entry Relations](https://github.com/robuust/craft-reverserelations) plugin? I'm not able to use an Entries Subset field as the Target Field, but with a regular Entries Field, I can.

**Comment by tinchalamo** [comment]
The developer of Reverse Entry Relations had this to say about what needs to be added to your plugin to make it compatible: https://github.com/robuust/craft-reverserelations/issues/5#issuecomment-483316407

**Comment by nfourtythree** [comment]
Hi @tinchalamo 

Thanks for bringing this to my attention. I have just pushed up a release that should hopefully sort your issue.

Thanks!

**Comment by tinchalamo** [comment]
@nfourtythree thanks for taking care of that so quickly! Works great.
